version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: always
